### ISSUE TITLE
Switch to alternative tools for sending emails

### ISSUE THREAD

**Issue by ttionya** [ttionya/vaultwarden-backup#117]
The tool for sending emails, `heirloom-mailx`, has been removed in Alpine v3.18.

Please refer to the issue (https://gitlab.alpinelinux.org/alpine/aports/-/issues/14791) and commit (https://gitlab.alpinelinux.org/alpine/aports/-/commit/8f375abf662d2f84ff9b132e8710d6e25eeaf80f) in the [Alpine/aports](https://gitlab.alpinelinux.org/alpine/aports) repository for more details.

Although it is possible to lock the Alpine version at 3.17, it is not an ideal solution. I prefer to continue using `rclone` as the base image, so we need to replace the email sending tool.

I plan to replace `heirloom-mailx` with `s-nail` because `heirloom-mailx` is a stub for `s-nail`. `s-nail` maintains a high degree of compatibility, although there may be some incompatible parts, the main options are compatible.

This change will take effect in the next version, and I am currently testing it.

**Comment by ttionya** [comment]
To avoid introducing disruptive changes to the backup tool, I will lock the `s-nail` version to `v14.9.x`. If in the future Alpine cannot provide an APK package for `v14.9`, we will compile and install s-nail ourselves.

**Comment by ttionya** [comment]
Starting from `v14.10` and future `v15` versions, `s-nail` will adopt a new MTA (Mail-Transfer-Agent) credential, and users will be alerted to switch to the new credential promptly. **As we will maintain s-nail `v14.9`**, users can **DISREGARD** warning messages similar to the following. Of course, you can choose to switch to using the MTA credential to eliminate these warning messages.

```bash
mail: Warning: variable superseded or obsoleted: smtp
mail: Warning: variable superseded or obsoleted: smtp-auth-user
mail: Warning: variable superseded or obsoleted: smtp-auth-password
mail: Obsoletion warning: please do not use *smtp*, instead assign a smtp:// URL to *mta*!
mail: Obsoletion warning: Use of old-style credentials, which will vanish in v15!
mail:   Please read the manual section "On URL syntax and credential lookup"
```

**Comment by kevdogg** [comment]
Hey I just wanted to chime in here a give another example for those that might want to avoid errors in the logs.  

-S v15-compat
-S mta=smtps://<user>:<password>@smtp.<domain>.com:465
-r bitwarden@<domain>.com(Bitwarden-Backup@archbw)
-S smtp-auth=login
-S ssl-protocol=-ALL,+TLSv1.3
-S ssl-verify=strict

**Comment by kevdogg** [comment]
Hey I've kind of revisited this issue recently, and here is my working config (which is variation of previous post):

```
-S v15-compat \
-S mta=smtps://<user>:<password>@smtp.<domain>.com:465 \
-S smtp-auth=login \
-S tls-ca-dir=/etc/ssl/certs \
-S tls-verify=strict \
-S tls-config-pairs='Protocol=TLSv1.3,Ciphersuites=TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256' \
-r "<username> <<username>@<hostname>>"
```

For the mta line, it possible to specify a specific port number if needbe.  Usually for smtps I'm either using port 465 or 587

If you do not want verification of the TLS certs you can omit the tls-ca-dir and tls-verify lines. 
This example is only using TLSv1.3.  I've specified specific Ciphersuites here for completeness, however if you just want the default set of Ciphersuites which is probably good for 99% of cases, you could also write is as:

```
-S tls-config-pairs='Protocol=TLSv1.3'
```

There are multiple ways to configure the return address, but I'm just showing this as an example.  The return address likely to get mangled by the MTA anyway.

**Comment by kevdogg** [comment]
@medir 
I remember struggling with this issue mightly for a very long time.  I don't really have an all inclusive solution since on the surface your configuration and testing seems sound.  I can only tell you how I was able to make it work.

Here are snippets of my compose file:
```
secrets:
  heirloom-mail-x_secret:
    file: ./heirloom-mail-x.secret
  7z_secret:
    file: ./7z.secret

  bitwarden-backup:
    container_name: bitwarden-backup
    hostname: bitwarden-backup
    image: ttionya/vaultwarden-backup:latest
    restart: always
    networks:
      - bitwarden_rs_net
    secrets:
      - heirloom-mail-x_secret
      - 7z_secret
    depends_on:
      <<: *bitwarden-depends
    healthcheck:
      <<: *bitwarden-backup-healthcheck
    ....
    ....
    environment:
      - RCLONE_REMOTE_NAME=${RCLONE_REMOTE_NAME}
      - RCLONE_REMOTE_DIR=/mnt/bitwarden-backup
#      - RCLONE_CONFIG_DIR=/config
      - CRON=0 */3 * * *
      - ZIP_ENABLE=TRUE
      - ZIP_TYPE=7z
      - ZIP_PASSWORD=/run/secrets/7z_secret
      - BACKUP_KEEP_DAYS=30
      - BACKUP_FILE_DATE_SUFFIX=-%X
      - TIMEZONE=${TZ}
      - MAIL_TO=<me>@gmail.com
      - MAIL_SMTP_ENABLE=TRUE
      - MAIL_SMTP_VARIABLES_FILE=/run/secrets/heirloom-mail-x_secret
      - MAIL_WHEN_SUCCESS=TRUE
      - MAIL_WHEN_FAILURE=TRUE
      - DATA_DIR=/data
      - DISPLAY_NAME=ttionya-mySQL.lite
```

In terms of the secrets file, the content of mine is similar:
```
-S v15-compat \
-S mta=smtps://<user>:<password>@postfix.<domain.com>:465 \
-S smtp-auth=login \
-S tls-ca-dir=/etc/ssl/certs \
-S tls-verify=strict \
-S tls-config-pairs='Protocol=TLSv1.3,Ciphersuites=TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256' \
-S 'from=Bitwarden Backup mySQL <bitwarden@backup.<domain>.com>'
```

I don't think the deprecation of berkely databases is going to effect this issue as I've seen this on some installation as they switch to lmdb
