### ISSUE TITLE
Backups should still be executed incase one target is "broken"

### ISSUE THREAD

**Issue by DELTAJoSch** [ttionya/vaultwarden-backup#175]
I recently had the problem that the backup was not executed as the entire container restarts if one rclone target is broken/misconfigured. Since I have multiple targets (to mitigate failures in any single backup target), none of them working if one is broken is a bit of an issue.

My configuration
```yaml
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: REDACTED
      SIGNUPS_ALLOWED: false # Restrict to invitations via damin page
      ADMIN_TOKEN: REDACTED
      PUSH_RELAY_URI: REDACTED
      PUSH_IDENTITY_URI: REDACTED
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: REDACTED
      PUSH_INSTALLATION_KEY: REDACTED
      USE_SYSLOG: true
      EXTENDED_LOGGING: true
      SMTP_HOST: REDACTED
      SMTP_PORT: 587
      SMTP_FROM: REDACTED
      SMTP_SECURITY: starttls
      SMTP_USERNAME: REDACTED
      SMTP_PASSWORD: REDACTED
    volumes:
      - vaultwarden-data:/data/
    ports:
      - 29800:80 # Change Host Port
  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    environment:
      CRON: '5 12 * * *' # Every Day at 12:05
      ZIP_ENABLE: 'TRUE'
      ZIP_PASSWORD: 'REDACTED'
      ZIP_TYPE: 'zip'
      BACKUP_FILE_SUFFIX: '%Y%m%d%I%M' # Year-Month-Day-Hour-Minute
      BACKUP_KEEP_DAYS: 3 # Discard Backups after 3 Days
      PING_URL: REDACTED
      PING_URL_CURL_OPTIONS: '-X GET'
    #   TIMEZONE: 'UTC' # Define if required
      RCLONE_REMOTE_NAME: Bitwarden-Backup-1
      RCLONE_REMOTE_DIR: /Vaultwarden-Backup/
      RCLONE_REMOTE_NAME_1: Bitwarden-Backup-2
      RCLONE_REMOTE_DIR_1: /Vaultwarden-Backup/
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/

volumes:
  vaultwarden-data:
    name: vaultwarden-data
```

Where Bitwarden-Backup-1 does not get executed if Bitwarden-Backup-2 is misconfigured (Backup target 2 is a google drive whose login expired)
