### ISSUE TITLE
Please Clarify on Installation

### ISSUE THREAD

**Issue by varad-kadam** [ttionya/vaultwarden-backup#191]
Hello, 
I'm still quite new to this, and confused on how to actually implemented this backup solution.

Original `docker compose` file:
```
version: '3'

services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "xxxx"  # Your domain; vaultwarden needs to know it's https to work properly with attachments
      ADMIN_TOKEN: xxxx
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: xxxx
      PUSH_INSTALLATION_KEY: xxxx
    volumes:
      - ./vw-data:/data
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:3012:3012"
```

New `docker compose file:
```
version: '3'

services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "xxxx"  # Your domain; vaultwarden needs to know it's https to work properly with attachments
      ADMIN_TOKEN: xxxx
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: xxxx
      PUSH_INSTALLATION_KEY: xxxx
    volumes:
      - ./vw-data:/data
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:3012:3012"
  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    environment:
      RCLONE_REMOTE_NAME: 'BitwardenBackup'
      RCLONE_REMOTE_DIR: '/BitwardenBackup/'
    #   RCLONE_GLOBAL_FLAG: ''
      CRON: '5 * * * *'
    #   ZIP_ENABLE: 'TRUE'
    #   ZIP_PASSWORD: 'WHEREISMYPASSWORD?'
    #   ZIP_TYPE: 'zip'
      BACKUP_FILE_SUFFIX: '%Y%m%d'
      BACKUP_KEEP_DAYS: 30
    #   PING_URL: ''
    #   PING_URL_CURL_OPTIONS: ''
    #   PING_URL_WHEN_START: ''
    #   PING_URL_WHEN_START_CURL_OPTIONS: ''
    #   PING_URL_WHEN_SUCCESS: ''
    #   PING_URL_WHEN_SUCCESS_CURL_OPTIONS: ''
    #   PING_URL_WHEN_FAILURE: ''
    #   PING_URL_WHEN_FAILURE_CURL_OPTIONS: ''
    #   MAIL_SMTP_ENABLE: 'FALSE'
    #   MAIL_SMTP_VARIABLES: ''
    #   MAIL_TO: ''
    #   MAIL_WHEN_SUCCESS: 'TRUE'
    #   MAIL_WHEN_FAILURE: 'TRUE'
      DATA_DIR: /data
      TIMEZONE: 'IST'
    volumes:
      - ./vw-data:/data/
      - ./vw-rclone-data:/config/
    #   - /path/to/env:/.env
```

However I'm still hit with:
```
 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults

CRITICAL: Failed to create file system for "BitwardenBackup:/BitwardenBackup": didn't find section in config file ("BitwardenBackup")

storage system connection failure [BitwardenBackup:/BitwardenBackup]

storage system connection failure exists
```

Kernel - Debian 6.1.21-v8+
rsync  version 3.2.7
rclone v1.60.1-DEV

I suspect it's just a misconfigured value, any pointers would be greatly appreciated.
