### ISSUE TITLE
cannot access /bitwarden/data: No such directory

### ISSUE THREAD

**Issue by hehecat** [ttionya/vaultwarden-backup#203]
不知道为什么一直提示 cannot access /bitwarden/data: No such directory

很确认配置中没有设置该目录
/mnt sudo docker inspect vaultwarden-backup-service | grep DATA_PATH
                "DATA_PATH=/vaultwarden-data/",

尝试把之前的Vaultwarden容器删了，用一个compose文件启动，还是爆同样的错误  cannot access /bitwarden/data: No such directory
```
version: '3.8'

services:
  vaultwarden: # Vaultwarden 服务本身
    image: vaultwarden/server:latest
    container_name: vaultwarden-service # 给它一个明确的容器名
    restart: unless-stopped # 与您之前的 inspect 结果一致
    environment:
      # --- 根据您的需求配置 Vaultwarden 环境变量 ---
      # SIGNUPS_ALLOWED: 'false'
      # ADMIN_TOKEN: 'YOUR_STRONG_ADMIN_TOKEN_HERE' # 强烈建议设置一个
      WEBSOCKET_ENABLED: 'true' # 推荐
      # ... 您可能需要的其他 Vaultwarden 特定环境变量 ...
      # ROCKET_PROFILE: 'release' # 这些通常是镜像内置的，可以不写
      # ROCKET_ADDRESS: '0.0.0.0'
      # ROCKET_PORT: '80'
    ports:
      - "8081:80" # 与您之前的 inspect 结果一致 (宿主机8081 -> 容器80)
    volumes:
      - /Container/vaultwarden:/data/ # Vaultwarden 容器内部数据路径通常是 /data/
                                     # 它会写入到宿主机的 /Container/vaultwarden
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backup: # 您的备份服务
    image: ttionya/vaultwarden-backup:latest
    container_name: vaultwarden-backup-service
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - APP_NAME=Vaultwarden
      - DATA_PATH=/vaultwarden-data/ # 备份容器内部读取数据的路径
      - BACKUP_PATH=/backup-output/vaultwarden-backup/
      - SAVE_REMOTE_TYPE=local
      - BACKUP_KEEP_DAYS=7
      - ZIP_ENABLE=TRUE
      # - ZIP_PASSWORD=YourStrongPassword # 记得取消注释并设置密码
      - DB_TYPE=sqlite
      - CRON="0 3 * * *"
    volumes:
      # 将宿主机的 Vaultwarden 数据目录映射到备份容器的 DATA_PATH
      - /Container/vaultwarden:/vaultwarden-data/:ro

      # 将宿主机的 NAS 备份挂载点目录映射到容器的 BACKUP_PATH
      - /mnt/backup:/backup-output/:rw
    # depends_on: # 可选，确保 vaultwarden 服务先启动
    #   - vaultwarden
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

```
