### ISSUE TITLE
Persistent 'rclone configuration not found' error despite valid and accessible config

### ISSUE THREAD

**Issue by aessaputra** [ttionya/vaultwarden-backup#204]
Hello,

I am experiencing a persistent rclone configuration information not found error on container startup, even after following all documentation and performing extensive troubleshooting.

The most important detail is that the rclone configuration works perfectly when I test it manually inside the running container as the correct user, but it fails when the container's entrypoint script runs automatically.

### My Configuration
`docker-compose.yml`
```yaml
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    user: 1002:1002
    restart: unless-stopped
    volumes:
      - vaultwarden-data:/data/
    environment:
      - ROCKET_WORKERS=20
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURITY=${SMTP_SECURITY}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SHOW_PASSWORD_HINT=false
      - DOMAIN=${DOMAIN}
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID=${PUSH_INSTALLATION_ID}
      - PUSH_INSTALLATION_KEY=${PUSH_INSTALLATION_KEY}
      - PUSH_RELAY_URI=${PUSH_RELAY_URI}
      - PUSH_IDENTITY_URI=${PUSH_IDENTITY_URI}
      - LOG_FILE=/data/vaultwarden.log
      - LOG_LEVEL=warn
      - EXTENDED_LOGGING=true
  backup:
    image: ttionya/vaultwarden-backup:latest
    container_name: vaultwarden-backup
    user: backuptool:backuptool
    restart: always
    environment:
      - RCLONE_REMOTE_NAME=${RCLONE_REMOTE_NAME}
      - RCLONE_REMOTE_DIR=${RCLONE_REMOTE_DIR}
      - RCLONE_GLOBAL_FLAG=${RCLONE_GLOBAL_FLAG}
      - CRON=${CRON}
      - ZIP_ENABLE=${ZIP_ENABLE}
      - ZIP_PASSWORD=${ZIP_PASSWORD}
      - ZIP_TYPE=${ZIP_TYPE}
      - BACKUP_FILE_SUFFIX=${BACKUP_FILE_SUFFIX}
      - BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS}
      - PING_URL=${PING_URL}
      - PING_URL_CURL_OPTIONS=${PING_URL_CURL_OPTIONS}
      - PING_URL_WHEN_START=${PING_URL_WHEN_START}
      - PING_URL_WHEN_START_CURL_OPTIONS=${PING_URL_WHEN_START_CURL_OPTIONS}
      - PING_URL_WHEN_SUCCESS=${PING_URL_WHEN_SUCCESS}
      - PING_URL_WHEN_SUCCESS_CURL_OPTIONS=${PING_URL_WHEN_SUCCESS_CURL_OPTIONS}
      - PING_URL_WHEN_FAILURE=${PING_URL_WHEN_FAILURE}
      - PING_URL_WHEN_FAILURE_CURL_OPTIONS=${PING_URL_WHEN_FAILURE_CURL_OPTIONS}
      - TIMEZONE=${TIMEZONE}
      - DATA_DIR=/bitwarden/data
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
networks:
  default:
    external: true
    name: nginxpm-nw
volumes:
  vaultwarden-data:
    name: vaultwarden-data
    external: true
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
```
### .env file (SENSITIVE VALUES REMOVED)
```
ADMIN_TOKEN=REDACTED
SMTP_HOST=REDACTED
SMTP_FROM=REDACTED
SMTP_PORT=465
SMTP_SECURITY=force_tls
SMTP_USERNAME=REDACTED
SMTP_PASSWORD=REDACTED
DOMAIN=REDACTED
PUSH_INSTALLATION_ID=REDACTED
PUSH_INSTALLATION_KEY=REDACTED
PUSH_RELAY_URI=https://api.bitwarden.eu
PUSH_IDENTITY_URI=https://identity.bitwarden.eu

RCLONE_REMOTE_NAME=BitwardenBackup
RCLONE_REMOTE_DIR=/BitwardenBackup/
RCLONE_GLOBAL_FLAG=--ipv4-only
CRON=5 * * * *
ZIP_ENABLE=TRUE
ZIP_PASSWORD=REDACTED
ZIP_TYPE=7z
BACKUP_FILE_SUFFIX=%Y%m%d
BACKUP_KEEP_DAYS=0
PING_URL=REDACTED
PING_URL_CURL_OPTIONS='-X POST -d "subject=%{subject}" -d "content=%{content}"'
PING_URL_WHEN_START=REDACTED
PING_URL_WHEN_START_CURL_OPTIONS=REDACTED
PING_URL_WHEN_SUCCESS=REDACTED
PING_URL_WHEN_SUCCESS_CURL_OPTIONS='-X POST -d "subject=%{subject}" -d "content=%{content}"'
PING_URL_WHEN_FAILURE=REDACTED
PING_URL_WHEN_FAILURE_CURL_OPTIONS='-X POST -d "subject=%{subject}" -d "content=%{content}"'
TIMEZONE=UTC
```
### Error Log
```
vaultwarden-backup  | ========================================
vaultwarden-backup  | rclone configuration information not found
vaultwarden-backup  | Please configure rclone first, check https://github.com/ttionya/vaultwarden-backup/blob/master/README.md#backup
```
### Troubleshooting & Diagnostics (This is the important part)
I have confirmed that the configuration file exists and is perfectly readable and usable by the backuptool user.
I ran docker compose exec -u backuptool vaultwarden-backup /bin/sh and performed these checks:

1. User is correct:
```bash
$ whoami
backuptool
$ id
uid=1100(backuptool) gid=1100(backuptool) groups=1100(backuptool)
```
2. Config file exists and has correct permissions:
```bash
$ ls -l /config/
-rw-r--r--    1 backuptool backuptool      112 Jun  7 10:30 rclone.conf
```
3. Config file is readable:
```bash
$ cat /config/rclone/rclone.conf
[BitwardenBackup]
type = mega
user = myemail@example.com
pass = REDACTED_PASSWORD
```
4. Rclone connection test SUCCEEDS:
```bash
$ rclone size BitwardenBackup:
Total objects: 755
Total size: 3.335 GiB (3580889248 Byte)
```
This proves that the user backuptool can read /config/rclone/rclone.conf and use it to successfully connect to the remote. The problem seems to be with how the entrypoint script is validating the configuration on startup.

I have already followed all steps in the documentation for running as a non-root user, including:

    Running chown -R 1100:1100 /config/ on the rclone volume.
    Running chmod -R +r /bitwarden/data/ on the vaultwarden data volume.

The issue persists even after all these steps. It seems like there might be a bug in the startup script.

Thank you for your help.
