### ISSUE TITLE
Can you explain the restore feature better?

### ISSUE THREAD

**Issue by kevdogg** [ttionya/vaultwarden-backup#46]
So I think I have everything about working however I'm really stuck on the restore process.

Here is my docker-compose service:

```
  bitwarden-backup:
    container_name: bitwarden-backup
    hostname: bitwarden-backup
    image: ttionya/vaultwarden-backup:latest
    restart: always
    networks:
      - bitwarden_rs_net
    secrets:
      - heirloom-mail-x_secret
    depends_on:
      <<: *bitwarden-depends
    volumes:
      - /home/bitwarden/.config/vaultwarden-backup:/config
      - /var/data/bw-data:/data
    environment:
      - RCLONE_REMOTE_NAME=arch-tm
      - RCLONE_REMOTE_DIR=/mnt/bitwarden-backup
      - CRON=*/5 * * * *
      - ZIP_ENABLE=TRUE
      - ZIP_TYPE=7z
      - BACKUP_KEEP_DAYS=30
      - BACKUP_FILE_DATE_SUFFIX=-%r
      - TIMEZONE=${TZ}
      - MAIL_SMTP_ENABLE=TRUE
      - MAIL_SMTP_VARIABLES_FILE=/run/secrets/heirloom-mail-x_secret
      - MAIL_WHEN_SUCCESS=TRUE
      - MAIL_WHEN_FAILURE=TRUE
      - DATA_DIR=/data
```

My config file is the following:

```
[arch-tm]
type = sftp
host = arch-tm.domain.com
user = bitwarden
key_file = ${RCLONE_CONFIG_DIR}/merged_key
pubkey_file = ${RCLONE_CONFIG_DIR}/merged_key
known_hosts_file = ${RCLONE_CONFIG_DIR}/known_hosts
md5sum_command = md5sum
sha1sum_command = sha1sum
```

On the remote server (the target of the backups), I have directory listings similar to the following:
```
'backup.20220304-01:10:00 AM.7z'  'backup.20220304-12:51:00 AM.7z'
'backup.20220304-01:15:00 AM.7z'  'backup.20220304-12:52:00 AM.7z'
'backup.20220304-01:20:00 AM.7z'  'backup.20220304-12:53:00 AM.7z'
'backup.20220304-01:25:00 AM.7z'  'backup.20220304-12:54:00 AM.7z'
'backup.20220304-12:46:00 AM.7z'  'backup.20220304-12:55:00 AM.7z'
'backup.20220304-12:47:00 AM.7z'  'backup.20220304-12:56:00 AM.7z'
'backup.20220304-12:48:00 AM.7z'  'backup.20220304-12:57:00 AM.7z'
'backup.20220304-12:49:00 AM.7z'  'backup.20220304-12:58:00 AM.7z'
'backup.20220304-12:50:00 AM.7z'  'backup.20220304-12:59:01 AM.7z'
```

Extracting one of the backups manually I get the following:

```
'config.20220304-01:10:00 AM.json'  'rsakey.20220304-01:10:00 AM.tar'
'db.20220304-01:10:00 AM.sqlite3'
```

So if I wanted manually to restore the backup -- I'd stop the vaultwarden container, and I could copy config.20220304-01:10:00 AM.json->config.json, db.20220304-01:10:00 AM.sqlite3->db.sqlite3, and manually extract the rsakeys and also restore all those.

I'm not sure however how to reverse the process. The example given in the documentation I didn't understand.

```
  --mount type=volume,source=vaultwarden-data,target=/bitwarden/data/ \
  --mount type=bind,source=$(pwd),target=/bitwarden/restore/ 
```

I don't see how the backup is going to restore over sftp -- I don't see a config file here anywhere this is mounted.  
Could you help with maybe more examples?

Oh one last thing although the mail test works, when trying to send mail from the program -- I'm getting this in my logs:
```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2022-03-04 03:00:01 ....A         1377        35008  config.20220304-03:00:01.json
2022-03-04 03:00:01 ....A       249856               db.20220304-03:00:01.sqlite3
2022-03-04 03:00:01 ....A         7680               rsakey.20220304-03:00:01.tar
------------------- ----- ------------ ------------  ------------------------
2022-03-04 03:00:01             258913        35008  3 files
upload backup file to storage system
delete 30 days ago backup files
mail send was successfully
send-mail: applet not found
```
No mail is actually sent when transfer is completed. successfully.
