### ISSUE TITLE
Ability to backup to mutliple rclone remotes

### ISSUE THREAD

**Issue by badi95** [ttionya/vaultwarden-backup#71]
First of all, thank you for your wonderful tool. I got it working backing up to my vps, but would like to also back up to a local directory that gets backed up to another remote site. Any plans to support multiple backup destinations?

**Comment by ttionya** [comment]
@badi95 ,

There are **no plans** that support simultaneous backups to multiple remote destinations.

You can specify multiple backup services in `docker-compose.yml`.

```yml
services:
  ...

  backup1:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    environment:
      RCLONE_REMOTE_NAME: 'remote1'
      RCLONE_REMOTE_DIR: '/BitwardenBackup/'
      CRON: '5 * * * *'
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/

  backup2:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    environment:
      RCLONE_REMOTE_NAME: 'remote2'
      RCLONE_REMOTE_DIR: '/BitwardenBackup/'
      CRON: '10 * * * *'
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
```

There are several reasons why this is not supported now.

Firstly, to support multiple remote destinations without break changes, one needs to consider how to add environment variables. The current design makes it difficult to add.

Secondly, how to notify? What kind of email should be sent when partial success. Especially ping, I don't know if I should send ping when partial success, now it this means this backup is successful.

Considering that users using this tool will not have particularly large backup data, multiple backups will not have a significant performance impact, and the notification address can be specified at a more granular level, I think the method I provided above is sufficient.

Hope to receive your comments.
