### ISSUE TITLE
docker compose: "rclone configuration information not found"

### ISSUE THREAD

**Issue by Barnoux** [ttionya/vaultwarden-backup#85]
Hello,

I followed the documentation to configure the rclone conf with the command:
```Shell
docker run --rm -it \
  --mount type=volume,source=vaultwarden-rclone-data,target=/config/ \
  ttionya/vaultwarden-backup:latest \
  rclone config show
```

In the docker volume : vaultwarden-rclone-data, we have the conf file who was correctly set.
But when i used docker compose. the remote name is the configuration file is BitwardenBackup.

With the service bellow, i have the error "rclone configuration information not found"

```yaml
[TRUNCATED]
backup:
    image: ttionya/vaultwarden-backup:latest
    user: 'backuptool:backuptool'
    volumes:
      - vaultwarden-data:/bitwarden/data
      - vaultwarden-rclone-data:/config

volumes:
  vaultwarden-data:
    name: vaultwarden-data
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
[TRUNCATED]
```
Did i miss something ? 

Regards,

BBA
